<?php

/**
 * Centralized API management and a
 */


function uas_menu() {
	$items = array();
	
	$items['admin/config/uas'] = array(
		'title' => 'UAS',
	    'description' => 'Central APIs for UAS modules',
	    'page callback' => 'uas_admin_landing_page',
	    'access arguments' => array('administer site configuration'),
	    'type' => MENU_NORMAL_ITEM
	);
	
	return $items;
}

/**
 * Implementation of hook_permission()
 */
function uas_permission() {
	return array(
		'administer uas settings' => array(
			'title'	=> t('Administer UAS Settings'),
			'description' => t('Perform administration tasks for UAS settings'),
			'restrict access' => TRUE
		)
	);
}

function uas_admin_landing_page() {
	
	return "This is a test and it's working";
	
}
