<?php

/**
 * Centralized API management and a
 */


function uas_menu() {
	$items = array();
	
	$items['admin/config/uas'] = array(
		'title' => 'UAS',
	    'description' => 'Central APIs for UAS modules',
	    'page callback' => 'uas_admin_landing_page',
	    'access arguments' => array('administer site configuration'),
	    'type' => MENU_NORMAL_ITEM
	);
	
	return $items;
}

/**
 * Implementation of hook_permission()
 */
function uas_permission() {
	return array(
		'administer uas settings' => array(
			'title'	=> t('Administer UAS Settings'),
			'description' => t('Perform administration tasks for UAS settings'),
			'restrict access' => TRUE
		)
	);
}

function uas_admin_landing_page() {
	
	return "This is a test and it's working";
	
}

function uas_theme() {
  return array(
    'uas_groups_block' => array(
      'variables' => array(
        'latest_content_block' => NULL,
        'latest_content_block_title' => NULL,
        'my_groups_block' => NULL,
        'my_groups_block_title' => NULL,
        'my_projects_block' => NULL,
        'my_projects_block_title' => NULL,
      ),
      'template' => 'uas_groups',
      'path' => drupal_get_path('module', 'uas').'/templates'
    )
  );
}

function uas_block_info() {
  return array(
    'uas_groups_block' => array(
      'info' => t('UAS Groups Content')
    )
  );
}

function uas_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'uas_groups_block':

      $block['content'] = array(
        '#theme' => 'uas_groups_block',
      );

      $views = array(
        'latest_group_content' => array(
          'target' => '#latest_content_block',
          'display_id' => 'block',
        ),
        'user_groups' => array(
          'target' => '#my_groups_block',
          'display_id' => 'block_1',
        ),
        'user_projects' => array(
          'target' => '#my_projects_block',
          'display_id' => 'block_1'
        ),
      );

      foreach($views as $view_name => $target_view) {
        $view = views_get_view($view_name);

        if(!$view || $view->access($target_view['display_id'])) {
          $block['content'][$target_view['target'] . "_title"] = '';
          $block['content'][$target_view['target']] = '';
        }

        $block['content'][$target_view['target'] . "_title"] = $view->get_title();
        $block['content'][$target_view['target']] = $view->preview($target_view['display_id']);
      }

      break;
  }

  return $block;
}