<?php

/**
 * Implementation of hook_views_default_views_alter().
 */
/*
function uas_maintenance_views_default_views_alter(&$views) {

  // Alter only the 'og_extras_groups' view.
  if (array_key_exists('og_extras_groups', $views)) {
    $views['og_extras_groups']->disabled = TRUE;
  }
}
/**/
/**
 * Implements hook_menu_block_blocks().
 */
/*
function uas_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'primary_navigation-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Primary Navigation',
      'level'       => 2,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
/**/